hipstertext = 'Aesthetic whatever Truffaut kale chips, bitters semiotics pickled shabby chic Intelligentsia small batch. Squid brunch artisan cliche keffiyeh bicycle rights, hoodie raw denim. Butcher chia vinyl lomo locavore distillery. Cosby sweater single-origin coffee chia flexitarian disrupt, meggings Blue Bottle occupy Helvetica bitters leggings. Drinking vinegar whatever XOXO, dreamcatcher bitters polaroid McSweeney\'s bespoke craft beer Shoreditch kale chips plaid post-ironic Williamsburg. PBR&B Etsy quinoa vinyl blog. 8-bit fashion axe deep v whatever.'

hodortext = 'Hodor. Hodor hodor... Hodor hodor hodor... Hodor hodor HODOR hodor, hodor hodor?! Hodor hodor - hodor... Hodor hodor hodor hodor hodor - hodor?! Hodor. Hodor hodor... Hodor hodor hodor - hodor... Hodor hodor hodor?! Hodor! Hodor hodor, hodor - hodor hodor hodor?! Hodor. Hodor hodor hodor hodor; hodor HODOR hodor, hodor hodor?'

sljtext = "Normally, both your asses would be dead as fucking fried chicken, but you happen to pull this shit while I'm in a transitional period so I don't wanna kill you, I wanna help you. But I can't give you this case, it don't belong to me. Besides, I've already been through too much shit this morning over this case to hand it over to your dumb ass."

beertext = "autolysis seidel, ipa, cask reinheitsgebot bitter. secondary fermentation carboy, hydrometer cask mash. crystal malt aerobic; cask conditioned ale specific gravity trappist hefe brewpub attenuation. aerobic hefe; yeast carboy balthazar scotch ale conditioning acid rest chocolate malt. abv heat exchanger crystal malt cask dextrin alcohol, hard cider. wit rims filter pitch noble hops bittering hops priming."

yorktext = "That's champion where there's muck there's brass will 'e 'eckerslike ne'ermind gi' o'er. Eeh will 'e 'eckerslike nay lad michael palin bloomin' 'eck. Nay lad dahn t'coil oil. Mardy bum tha knows cack-handed. Bloomin' 'eck ah'll gi' thi summat to rooer abaht tintintin. Shu' thi gob where there's muck there's brass sup wi' 'im. Nobbut a lad ah'll box thi ears where's tha bin shurrup where there's muck there's brass tha what. That's champion michael palin ah'll gi' thee a thick ear. Soft lad is that thine face like a slapped arse where there's muck there's brass ey up. How much what's that when it's at ooam is that thine. That's champion a pint 'o mild nobbut a lad that's champion appens as maybe. Is that thine any rooad ah'll gi' thee a thick ear gi' o'er. Appens as maybe dahn t'coil oil tell thi summat for nowt. Soft lad nay lad god's own county tell thi summat for nowt wacken thi sen up shurrup. Tha knows aye."

webtext = "Webtwo ipsum dolor sit amet, eskobo chumby doostang bebo. Zapier lala omgpop zanga omgpop dogster xobni edmodo, dropio elgg foodzie jumo cuil vimeo insala, rovio divvyshot imvu octopart prezi elgg zoho. Buttera gooru reddit imeem qeyno hipmunk, dropio unigo zynga wesabe ifttt revver, akismet chumby sococo babblely. Scribd sclipo bebo wakoopa yuntaa balihoo zoodles wikia lanyrd bubbli, geni foodzie nuvvo edmodo appjet lala kosmix kaboodle omgpop, kno greplin zynga sifteo qeyno oovoo rovio edmodo. Yoono joukuu kaboodle lanyrd tivo, octopart sclipo orkut dropio, oooooc mog ebay. Twones loopt voki reddit heroku movity, mobly joyent kazaa voxy."

bluthtext = "And although the intervention didn't work, it turned into one of the Bluth family's better parties. I prematurely shot my wad on what was supposed to be a dry run..so now I'm afraid I have something of a mess on my hands. Although George Michael had only got to second base, he'd gone in head first, like Pete Rose. I want to cry so bad, but I don't think I can spare the moisture."

corporatetext = "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI"

downtontext = "Major Charles Bryant employed an affair. But it's not an engagement yet, is it, expounded Mr. Bryant. Miss Smith observed, How do you know that?! Have you been poking around in my things? Mrs. Isobel Crawley chattered, You don't care about Matthew getting everything because you don't think I'm worthy of it. Mrs. Bryant pronounced, No it was quite plain. O'Brien told her Bates can't do the job properly. Why was he taken on?"

yolotext = "Donec accumsan consectetur faucibus. YOLO, you only live once. Donec eget semper eros. Vestibulum lobortis eros vel elementum suscipit. Nunc tempus lectus elit, et faucibus ligula dignissim nec. Phasellus in turpis porta, laoreet sapien vitae, auctor ante.  Your chick, she so thirsty, nec consequat dui imperdiet eget. In quis rhoncus sem, eu eleifend purus. Etiam sodales turpis volutpat ultricies blandit. #Swaggityswag Donec pretium tincidunt mi, id semper dolor commodo eget."

bacontext = "Prosciutto turkey pork picanha capicola shankle. Beef doner leberkas, capicola short ribs ham filet mignon boudin pork jerky pancetta kevin short loin. Tongue rump tail, pork belly turkey chuck brisket cupim shank tri-tip landjaeger sausage. Bacon pig shank, kevin tri-tip t-bone alcatra chicken fatback pancetta meatball."

content = [hipstertext, hodortext, sljtext, beertext, yorktext, webtext, bluthtext, corporatetext, downtontext, yolotext, bacontext]

subjects = ["MOFN", "ONYON RENG", "BLANABBA", "MERSHED PERDERDER", "GURPS", "MONGO", "PEESH", "SHRAMP", "ERNJ JEWS", "SPOGOOTER", "TARDERTOOT", "SHARDED BARF", "BURSL PROTS", "BOCAN DARBLE CHAISE BARGA", "ACVODAD", "SPEGY N MERBLS", "FEWT", "AISE KROM", "PASIKLE", "SIRL", "MORK"]

requesters = ["Sterling Archer", "Lana Kane", "Malory Archer", "Cyril Figgis", "Cheryl Tunt", "Pam Poovey", "Dr. Krieger", "Ray Gillette", "Woodhouse"]

requesteremails = ["s.archer@fakeisisdomain.com", "l.kane@fakeisisdomain.com", "m.archer@fakeisisdomain.com", "c.figgis@fakeisisdomain.com", "c.tunt@fakeisisdomain.com", "p.poovey@fakeisisdomain.com", "krieger@fakeisisdomain.com", "r.gillette@fakeisisdomain.com", "woodhouse@fakeisisdomain.com"]